server {
    listen 80;

    location / {
        try_files $uri /index.html;
    }

    location /auth/ {
        proxy_pass http://backend:8080/auth/;
    }

    location /users/ {
        proxy_pass http://backend:8080/users/;
    }
}