spring.application.name=webapp-backend

spring.datasource.url=jdbc:postgresql://192.168.1.203:5432/user
spring.datasource.username=raspberry
spring.datasource.password=Hsvsa322

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true